# -*- coding: utf-8 -*-
"""Untitled76.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z2RHo9g_QFOEZpeLNLpN7iwKuEWq82Db
"""

for i in range(1,101):
    if (i%3==0 and i%5==0):
        print("FizzBuzz")
    elif i%3==0:
      print("Fizz")
    elif i%5==0:
      print("Buzz")
    else:
       print(i)